name: stanford-corenlp Python Mircoservice Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MAJOR_VERSION: 3
  MINOR_VERSION: 11
  MICRO_VERSION: 5

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            woped/stanford-corenlp-microservice:latest
            woped/stanford-corenlp-microservice:${{ env.MAJOR_VERSION }}
            woped/stanford-corenlp-microservice:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
            woped/stanford-corenlp-microservice:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.MICRO_VERSION }}
